### ISSUE TITLE
`SyntaxError: Object literal may not have data and accessor property with the same name`

### ISSUE THREAD

**Issue by nantas** [fireball-x/firedoc#24]
I run `firedoc path/to/source` and get the following error:

``` bash
error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: /Users/nantas/.nvm/versions/node/v0.12.0/lib/node_modules/firedoc/lib/builder.js:1165
    get files () {
        ^^^^^
SyntaxError: Object literal may not have data and accessor property with the same name
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Function.Y.Get._exec (/Users/nantas/.nvm/versions/node/v0.12.0/lib/node_modules/firedoc/node_modules/yui/yui-nodejs/yui-nodejs.js:4095:13)
    at Function.Y.Get._include (/Users/nantas/.nvm/versions/node/v0.12.0/lib/node_modules/firedoc/node_modules/yui/yui-nodejs/yui-nodejs.js:4155:19)
    at Function.Y.Get.js (/Users/nantas/.nvm/versions/node/v0.12.0/lib/node_modules/firedoc/node_modules/yui/yui-nodejs/yui-nodejs.js:4183:19)
    at Object.Y.Loader._insert (/Users/nantas/.nvm/versions/node/v0.12.0/lib/node_modules/firedoc/node_modules/yui/yui-nodejs/yui-nodejs.js:7537:19)
    at /Users/nantas/.nvm/versions/node/v0.12.0/lib/node_modules/firedoc/node_modules/yui/yui-nodejs/yui-nodejs.js:7590:18
    at Object.Y.Loader._continue (/Users/nantas/.nvm/versions/node/v0.12.0/lib/node_modules/firedoc/node_modules/yui/yui-nodejs/yui-nodejs.js:7573:26)
    at Object.Y.Loader.insert (/Users/nantas/.nvm/versions/node/v0.12.0/lib/node_modules/firedoc/node_modules/yui/yui-nodejs/yui-nodejs.js:7592:14)
    at proto._use (/Users/nantas/.nvm/versions/node/v0.12.0/lib/node_modules/firedoc/node_modules/yui/yui-nodejs/yui-nodejs.js:1313:20)
error: --------------------------------------------------------------------------
error: Node.js version: v0.12.0
error: YUI version: 3.18.1
error: YUIDoc version: 1.5.4
error: Please file all tickets here: http://github.com/fireball-x/firedoc/issues
error: --------------------------------------------------------------------------
```

**Comment by yorkie** [comment]
Thanks @nantas this is because I introduced a naming conflicts on `builder.files`, now it gets fixed at `firedoc@1.5.6`.
